# .github/dependabot.yml
version: 2
updates:
  # Update dependencies for the template itself
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Update pre-commit hooks for the template
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Update GitHub Actions in the template
  - package-ecosystem: "github-actions"
    directory: "/{{cookiecutter.project_slug}}/.github"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Update dependencies for generated projects (for testing)
  - package-ecosystem: "pip"
    directory: "/{{cookiecutter.project_slug}}"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
