# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "pip" # For Python projects
    directory: "/{{cookiecutter.project_slug}}" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
