import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest
from cookiecutter.main import cookiecutter


@pytest.fixture(scope="session")
def generated_project_path(tmp_path_factory):
    """Fixture to generate a project from the cookiecutter template and return its path."""
    template_dir = Path(__file__).parent.parent
    output_dir = tmp_path_factory.mktemp("generated_project")

    # Default context for the cookiecutter template
    # These values will be used to generate the project without user input
    context = {
        "project_name": "Test Project",
        "project_slug": "test_project",
        "project_description": "A test project generated by cookiecutter.",
        "author_name": "Test Author",
        "author_email": "test@author.com",
        "python_version": "3.11",
        "github_username": "testuser",
        "github_reponame": "test-repo",
    }

    # Generate the project
    project_path = cookiecutter(
        template=str(template_dir),
        no_input=True,
        extra_context=context,
        output_dir=output_dir,
    )

    return Path(project_path)


def test_project_generation(generated_project_path: Path):
    """Test that the project is generated successfully with the correct structure."""
    assert generated_project_path.is_dir()
    assert (generated_project_path / "pyproject.toml").is_file()
    assert (generated_project_path / "src" / "test_project").is_dir()
    assert (generated_project_path / "tests").is_dir()


def test_makefile_all_command(generated_project_path: Path):
    """
    Test that the 'make all' command runs successfully in the generated project.

    This verifies that dependencies are installed and the git repo is initialized.
    """
    # The 'remotegit' target might fail if the test machine doesn't have git configured
    # or can't reach github, so we run the essential targets separately.

    # Find `uv` executable to ensure it's on the PATH for the subprocess
    uv_path = shutil.which("uv")
    assert uv_path, "uv executable not found in PATH"
    uv_dir = str(Path(uv_path).parent)

    # Get the current environment and add the uv path
    env = os.environ.copy()
    env["PATH"] = f"{uv_dir}:{env['PATH']}"
    env["SHELL"] = "/bin/bash"
    env["uv_python"] = sys.executable

    # We need to make sure we use the same python that runs the test
    make_command_uv = [
        "make",
        "-C",
        str(generated_project_path),
        "uv",
    ]

    # Run 'make uv'
    result_uv = subprocess.run(  # noqa: S603
        make_command_uv,
        capture_output=True,
        text=True,
        env=env,
    )

    assert result_uv.returncode == 0, (
        f"make uv failed with output:\\n{result_uv.stdout}\\n{result_uv.stderr}"
    )

    # Run 'make git'
    make_command_git = ["make", "-C", str(generated_project_path), "git"]
    result_git = subprocess.run(  # noqa: S603
        make_command_git,
        capture_output=True,
        text=True,
        env=env,
    )

    assert result_git.returncode == 0, (
        f"make git failed with output:\\n{result_git.stdout}\\n{result_git.stderr}"
    )
